spring.application.name=GasProject

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.username=postgres
spring.datasource.password=mahipsql
spring.datasource.url=jdbc:postgresql://localhost:5432/gasdb


app.upi.id=mahiyadav8185@ibl
app.upi.name=Gas Booking
